branch-defaults:
  dev:
    environment: akatosh-api
    group_suffix: null
  main:
    environment: akatosh-production-api
    group_suffix: null
global:
  application_name: akatosh-production-api
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: akatosh-deploy
  repository: null
  sc: git
  workspace_type: Application
